<a href="https://colab.research.google.com/github/genie0320/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy For Machine Learning

Numpy는 list다루는 특별한 모듈이다.   
list에는 여러가지 자료형이 한번에 담길 수 있고, 이를 편하게 다룰 수 있도록 도와주는 모듈이다.

Numpy는 Numeric Python 이라는 뜻.
ndarray = n - dimentional array

## Create Numpy array (ndarray)

In [2]:
normail_python_list = [0,1,2,3,4,5,6,7,8,9]
normail_python_list # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
import numpy as np

# convert python list to numpy array
numpy_array = np.array(normail_python_list)
print(numpy_array) # [0 1 2 3 4 5 6 7 8 9]
numpy_array # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
numpy_array.shape

(10,)

- 이렇게 자동으로 값을 만들어낼 수도 있다.  
    - np.~ ((차원의 수, 각 차원당 자료의 갯수))  


In [15]:
# 1차원 자료
np.arange(10) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(0,10,2) # array([0, 2, 4, 6, 8])

# 다차원 자료
# np.~ ((차원의 수, 각 차원당 자료의 갯수))
np.zeros(10) # array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
np.zeros((2,10)) # array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                 #        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
# np.~ ((차원의 수), 채울 자료)
np.full((10), 6) # array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])
np.full((2, 10), 8) # array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
                    #        [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

## Slicing Numpy Arrays

In [16]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [25]:
np1[1:5] # array([2, 3, 4, 5])
np1[:3] # array([1, 2, 3])
np1[3:] # array([ 4,  5,  6,  7,  8,  9, 10])
np1[-3:-1] # array([8, 9])

# steps
np1[1:5] # array([2, 3, 4, 5])
np1[1:5:2] # array([2, 4])
np1[::3] # array([ 1,  4,  7, 10])

array([ 1,  4,  7, 10])

In [31]:
np2 = np.array((2,5))
np.full((2,10),np.arange(10)) # array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                              #        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
np2 = np.full((2,10),np.arange(10))
np2[0:2, 1:3] # array([[1, 2],
              #        [1, 2]])

array([[1, 2],
       [1, 2]])

## Numpy Universal Functions

## Etc.

행렬
    - 동일 크기의 행렬/벡터만 더하기 가능. > python 예외 있음.
    - 2*3 , 3*4는 곱하기 가능(중간의 두 숫자가 같음) 결과는 양쪽 숫자의 모양이 됨. 즉 2*4 가 결과로 나올거임. (곱하기는 이쪽 열과 저쪽 행을 차례로 곱해서 하나의 숫자가 될 때까지 더해서 나온 것이 그 자리의 수가 됨. 여튼 매우 귀찮)

* python 예외 : 행렬 + 1 하면, 행렬의 모든 요소에 1를 더한 상태로 계산되어 나온다. 신기하징?